[workspace]
members = [
    "app",
    "consensus",
    "p2p",
]
resolver = "2"

[workspace.dependencies]
hotstuff-consensus = { version = "0.1.0", path = "consensus" }
hotstuff-p2p = { version = "0.1.0", path = "p2p" }

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"
license = "MIT"
