[client]
nodes = ["127.0.0.1:50011", "127.0.0.1:50012", "127.0.0.1:50013", "127.0.0.1:50014"]

[[nodes]]
public_key = "i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX"
secret_key = "Z83efxRRrF26MRgUwPbtEB116kTVJuRJ3kCsUyXTPsU="
committee = ["i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX",
             "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18",
             "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy",
             "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy"]
hotstuff.mailbox_size = 256
hotstuff.timeout = 5000
rpc.address = "127.0.0.1:50011"
network.peer_manager.min_peers = 3
network.peer_manager.max_peers = 10
network.peer_manager.mailbox_size = 256
network.peer_manager.peers = {"uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18" = "127.0.0.1:30012", "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy" = "127.0.0.1:30013", "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy" = "127.0.0.1:30014"}
network.peer_manager.handshake_timeout = 1000
network.dialer.interval = 200
network.listener.address = "127.0.0.1:30011"
network.mailbox_size = 256

[[nodes]]
public_key = "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18"
secret_key = "CiIwL90zs9hzJFT0UjnhXtENobj/EE0sTR3ZCMVEtLo="
committee = ["i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX",
             "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18",
             "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy",
             "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy"]
hotstuff.mailbox_size = 256
hotstuff.timeout = 5000
rpc.address = "127.0.0.1:50012"
network.peer_manager.min_peers = 3
network.peer_manager.max_peers = 10
network.peer_manager.mailbox_size = 256
network.peer_manager.peers = {"i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX" = "127.0.0.1:30011", "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy" = "127.0.0.1:30013", "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy" = "127.0.0.1:30014"}
network.peer_manager.handshake_timeout = 1000
network.dialer.interval = 200
network.listener.address = "127.0.0.1:30012"
network.mailbox_size = 256

[[nodes]]
public_key = "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy"
secret_key = "E8MbhDO6hjtgw1RZKTfsAU9muGgtbDHnz3c8K5lBOwM="
committee = ["i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX",
             "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18",
             "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy",
             "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy"]
hotstuff.mailbox_size = 256
hotstuff.timeout = 5000
rpc.address = "127.0.0.1:50013"
network.peer_manager.min_peers = 3
network.peer_manager.max_peers = 10
network.peer_manager.mailbox_size = 256
network.peer_manager.peers = {"i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX" = "127.0.0.1:30011", "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18" = "127.0.0.1:30012", "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy" = "127.0.0.1:30014"}
network.peer_manager.handshake_timeout = 1000
network.dialer.interval = 200
network.listener.address = "127.0.0.1:30013"
network.mailbox_size = 256

[[nodes]]
public_key = "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy"
secret_key = "EML5KO5Ipj5P1D47PE808kTDik9gPDZ9ZUzVvKHI0Z8="
committee = ["i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX",
             "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18",
             "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy",
             "lKu+NQoV+I7bhzRqUiQ6b6TPP1eB6L2mx6KAploebqto/s9MSQ6aPRelOZeQ3Gyy"]
hotstuff.mailbox_size = 256
hotstuff.timeout = 5000
rpc.address = "127.0.0.1:50014"
network.peer_manager.min_peers = 3
network.peer_manager.max_peers = 10
network.peer_manager.mailbox_size = 256
network.peer_manager.peers = {"i2fMEOfoXEFOtOl9txFy8WRLPJIeEQZ5rYX9s/KY9YxTVg9/9etxyCIrfdPQCRkX" = "127.0.0.1:30011", "uVddny195j67qlZjkqy+bAIphC7w6/QPyQGpdyJwZp19yG9OXZKFtQEkmQESZa18" = "127.0.0.1:30012", "mIagyVMaP3iZTJ1oqv07xpbeEUDYNO3GKg+HLgrJh4LQHB0bMEeOGyw4MNCb3nmy" = "127.0.0.1:30013"}
network.peer_manager.handshake_timeout = 1000
network.dialer.interval = 200
network.listener.address = "127.0.0.1:30014"
network.mailbox_size = 256
